# version: '3.7'

services:

  #MQTT message broker 
  rabbitmq:
    container_name: pimview-rabbitmq
    build:
      context: rabbitmq
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 15675:15675
      - 15676:15676
      - 1883:1883
      - 15000:15000
      - 8883:8883
    volumes:
      - ./rabbitmq/config/:/etc/rabbitmq/
    networks:
      - pimview-network
    environment:
      - RABBITMQ_CONFIG_FILE=${PIMVIEW_RABBITMQ_MQTT_CONFIG_FILE}
      - RABBITMQ_DEFAULT_USER=${PIMVIEW_RABBITMQ_MQTT_USER}
      - RABBITMQ_DEFAULT_PASS=${PIMVIEW_RABBITMQ_MQTT_PASSWORD}
      - PIMVIEW_RABBITMQ_MQTT_USER=${PIMVIEW_RABBITMQ_MQTT_USER}
      - PIMVIEW_RABBITMQ_MQTT_PASSWORD=${PIMVIEW_RABBITMQ_MQTT_PASSWORD}

  # app:
  #   image: node:18-alpine
  #   command: sh -c "yarn install && yarn run dev"
  #   ports:
  #     - 127.0.0.1:3000:3000
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: secret
  #     MYSQL_DB: todos

  pimview-frontend-core:
    container_name: pimview-frontend-core
    image: blambo10/pimview-frontend-core
    restart: always
    ports:
      - 80:80
    depends_on:
      - rabbitmq
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
      - REACT_APP_PIMVIEW_DEVICE_URL=${REACT_APP_PIMVIEW_DEVICE_URL}
    networks:
      - pimview-network
    
  pimview-denonavr-sub:
    image: blambo10/pimview-denonavr-service-backend:latest
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - MQTT_BROKER_ADDRESS=${PIMVIEW_MQTT_BROKER_ADDRESS}
      - MQTT_BROKER_USERNAME=${PIMVIEW_RABBITMQ_MQTT_USER}
      - MQTT_BROKER_PASSWORD=${PIMVIEW_RABBITMQ_MQTT_PASSWORD}
      - DEVICE_ADDRESS=${PIMVIEW_MARANTZ_DEVICE_ADDRESS}
      - DEVICE_PORT=${PIMVIEW_MARANTZ_DEVICE_PORT}
    networks:
      - pimview-network
    
  pimview-denonavr-pub:
    image: blambo10/pimview-denonavr-service-backend:latest
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - MQTT_BROKER_ADDRESS=${PIMVIEW_MQTT_BROKER_ADDRESS}
      - MQTT_BROKER_USERNAME=${PIMVIEW_RABBITMQ_MQTT_USER}
      - MQTT_BROKER_PASSWORD=${PIMVIEW_RABBITMQ_MQTT_PASSWORD}
      - DEVICE_ADDRESS=${PIMVIEW_MARANTZ_DEVICE_ADDRESS}
      - DEVICE_PORT=${PIMVIEW_MARANTZ_DEVICE_PORT}
      - RUN_PUBLISHER=true
    networks:
      - pimview-network
          
  pimview-denonavr-frontend-module:
    image: blambo10/pimview-denonavr-service-frontend:latest
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - rabbitmq
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_PIMVIEW_RABBITMQ_MQTT_ADDRESS=${PIMVIEW_EXTERNAL_MQTT_BROKER_ADDRESS}
      - REACT_APP_PIMVIEW_RABBITMQ_MQTT_USER=${PIMVIEW_RABBITMQ_MQTT_USER}
      - REACT_APP_PIMVIEW_RABBITMQ_MQTT_PASSWORD=${PIMVIEW_RABBITMQ_MQTT_PASSWORD}
      - REACT_APP_PIMVIEW_RABBITMQ_MQTT_PORT=${PIMVIEW_RABBITMQ_MQTT_PORT}
    networks:
      - pimview-network

  # pimview-lg:
  #   build: https://github.com/blambo10/pimview-lg-service.git#main
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     - MQTT_BROKER_ADDRESS=${PIMVIEW_MQTT_BROKER_ADDRESS}
  #     - MQTT_BROKER_USERNAME=${PIMVIEW_RABBITMQ_MQTT_USER}
  #     - MQTT_BROKER_PASSWORD=${PIMVIEW_RABBITMQ_MQTT_PASSWORD}
  #     - WEB_OS_ADDRESS=192.168.1.36
  #   networks:
  #     - pimview-network

networks:
  pimview-network:
    driver: bridge