version: '3.7'

services:

  rabbitmq:
    container_name: pimview-rabbitmq
    build:
      context: rabbitmq
      dockerfile: dockerfile
    restart: always
    ports:
      - 15675:15675
      - 1883:1883
    environment:
      - RABBITMQ_DEFAULT_USER=${PIMVIEW_RABBITMQ_MQTT_USER}
      - RABBITMQ_DEFAULT_PASS=${PIMVIEW_RABBITMQ_MQTT_PASSWORD}
      - PIMVIEW_RABBITMQ_MQTT_USER=${PIMVIEW_RABBITMQ_MQTT_USER}
      - PIMVIEW_RABBITMQ_MQTT_PASSWORD=${PIMVIEW_RABBITMQ_MQTT_PASSWORD}